# Generated by Django 3.0.8 on 2020-07-23 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0002_auto_20200723_2322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bloodbank',
        ),
    ]
